wandb_version: 1

gamma:
  desc: null
  value: 0.8
lr:
  desc: null
  value: 1
strat_val:
  desc: null
  value: 0.1
_wandb:
  desc: null
  value:
    python_version: 3.11.6
    cli_version: 0.16.2
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1708336288.957601
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.11.6
      5: 0.16.2
      8:
      - 1
      - 5
      13: linux-x86_64
