wandb_version: 1

activation_functions:
  value: relu
batch_size:
  value: 32
learning_rate:
  value: 0.0001
number_of_epochs:
  value: 10
number_of_hidden_layers:
  value: 4
optimizer:
  value: adam
size_of_every_hidden_layer:
  value: 32
weight_decay:
  value: 0.0005
weight_initialisation:
  value: xavier_normal
