wandb_version: 1

activation_functions:
  value: tanh
batch_size:
  value: 64
learning_rate:
  value: 0.0001
number_of_epochs:
  value: 5
number_of_hidden_layers:
  value: 3
optimizer:
  value: adam
size_of_every_hidden_layer:
  value: 64
weight_decay:
  value: 0
weight_initialisation:
  value: xavier_normal
