wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.5
    cli_version: 0.16.0
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1700185670.816599
    t:
      1:
      - 2
      - 3
      - 12
      - 55
      2:
      - 2
      - 3
      - 12
      - 55
      3:
      - 2
      - 14
      - 23
      4: 3.11.5
      5: 0.16.0
      8:
      - 1
      - 5
      13: linux-x86_64
