wandb_version: 1

activation_functions:
  value: tanh
batch_size:
  value: 16
learning_rate:
  value: 0.001
number_of_epochs:
  value: 10
number_of_hidden_layers:
  value: 5
optimizer:
  value: rmsprop
size_of_every_hidden_layer:
  value: 32
weight_decay:
  value: 0.0005
weight_initialisation:
  value: random
