wandb_version: 1

activation_functions:
  value: tanh
batch_size:
  value: 32
learning_rate:
  value: 0.0001
number_of_epochs:
  value: 10
number_of_hidden_layers:
  value: 5
optimizer:
  value: momentum
size_of_every_hidden_layer:
  value: 128
weight_decay:
  value: 0
weight_initialisation:
  value: xavier_normal
