wandb_version: 1

activation_functions:
  value: relu
batch_size:
  value: 64
learning_rate:
  value: 0.0001
number_of_epochs:
  value: 10
number_of_hidden_layers:
  value: 5
optimizer:
  value: rmsprop
size_of_every_hidden_layer:
  value: 64
weight_decay:
  value: 0.5
weight_initialisation:
  value: random
