wandb_version: 1

activation_functions:
  value: sigmoid
batch_size:
  value: 32
learning_rate:
  value: 0.001
number_of_epochs:
  value: 10
number_of_hidden_layers:
  value: 4
optimizer:
  value: sgd
size_of_every_hidden_layer:
  value: 64
weight_decay:
  value: 0.0005
weight_initialisation:
  value: random
